server:
  port: 8082
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:studentdb
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles:
    active: local, clean
  application:
    name: STUDENT-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  file:
    name: logs/local/student-service.log
